name: Cocktail
title: Cocktail | Your Daily cocktail of knowledge
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: الرئيسية
    url: /
  - title: من نحن
    url: /من نحن
  - title: راسلنا
    url: /راسلنا
categorie:
  - title: الشركات الناشئة
    url: /category/الشركات الناشئة
  - title: التكنولوجيا
    url: /category/التكنولوجيا
  - title: التسويق
    url: /category/التسويق
  - title: شؤون ريادية
    url: /category/شؤون ريادية
  - title: مفاهيم
    url: /category/مفاهيم
  - title: نجاح و إخفاق
    url: /category/نجاح و إخفاق
  - title: كيف أبدأ
    url: /category/كيف أبدأ
  - title: أدوات
    url: /category/أدوات
email: thisiscocktail.blog@gmail.com
disqus_username: thisiscocktail
